# Data Analysis in Python


<img src="images/analysis_header.png" width=500 />

In [14]:
#site for dataset
#https://github.com/sentinelsat/sentinelsat
#https://github.com/16EAGLE/getSpatialData
#https://earthexplorer.usgs.gov/
#https://scihub.copernicus.eu/
#https://espa.cr.usgs.gov/
#https://earthdata.nasa.gov/
#https://ipywidgets.readthedocs.io/en/latest/user_install.html
#https://data.humdata.org/dataset/burkina-faso-administrative-boundaries
#http://www.citypopulation.de/en/burkinafaso/
#https://www.usgs.gov/land-resources/nli/landsat/landsat-shapefiles-and-kml-files
#https://www.esa.int/Applications/Observing_the_Earth/Copernicus/Sentinel-5P
#https://sentinel.esa.int/web/sentinel/toolboxes/sentinel-1
#https://github.com/johntruckenbrodt/pyroSAR
#https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjZ_dL2sJXrAhULJBoKHV0VB8gQFjADegQIBBAB&url=https%3A%2F%2Fwww.mdpi.com%2F2504-3900%2F18%2F1%2F11%2Fpdf&usg=AOvVaw3bGHqYDu96DRH_MpW96Z7q
#radar processing sentinel1//file:///tmp/mozilla_sth02bh0/proceedings-18-00011.pdf
#https://drive.google.com/file/d/1Vie8hyB38wdBJpH5Lkv7thgLiUwbi1w4/view?usp=sharing
#https://gdal.org/programs/gdal_polygonize.html
#<img src="images/reflectance.jpg" width="800" /> 
#Source:https://seos-project.eu/remotesensing/remotesensing-c01-p06.html
#https://gdal.org/programs/gdal_polygonize.html

## The mighty three

- NumPy: "[NumPy](http://www.numpy.org) is the fundamental package for scientific computing with Python*"

- Pandas: "[pandas](https://pandas.pydata.org) is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language*"

- Matplotlib: "[Matplotlib](https://matplotlib.org) is a Python 2D plotting library which produces publication quality figures in a variety of hardcopy formats and interactive environments across platforms*"

<img src="images/mighty3.png" />

## Installation

You can always check here: https://anaconda.org/

conda install numpy

conda install pandas

conda install matplotlib

OR

pip install numpy

pip install pandas

pip install matplotlib



##### Data types 

<img src="images/types.png"  />

## Fast, faster, NumPy

<img src="images/numpy.png"  width=200 align=right />

Numpy allows us to run mathematical operations over calculations in a efficiant manner. 
Numpy provides several advantages for python user:

- powerful n-dimensional arrays
- advanced functions
- can integrate C/C++ and Fortran code
- efficient linear  algebra, random number generation and Fourier transformation 



## Numpy arrays

The core class is the numpy ndarray (n-dimensional array). We can initialize a numpy array from nested Python lists.

In [4]:
# create numpy array
import numpy as np

# 1d array
a = np.array([1, 2, 3, 4 , 5, 6])

# 2d array
b = np.array([[1, 2, 3,4 , 5, 6],[1, 2, 3,4 , 5, 6]])

# 3d array
c = np.array([[[1,2,3,4], [5,6,7,8], [9,10,11,12],[13,14,15,16]],[[1,2,3,4], [5,6,7,8], [9,10,11,12],[13,14,15,16]]])

In [6]:
# create an array from a list
a = np.arange(18).reshape(3, 3, 2)
print(a)
# find out the datatype
print(a.dtype)
# find out the shape
a.shape

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
int64


(3, 3, 2)

<img src="images/array.png" width=200 />

### Vectorization

When looping over a list or an array, there’s a lot of overhead involved. Vectorized operations in NumPy delegate the looping internally to highly optimized C and Fortran functions.


In [7]:
# traditional python

a = list(range(100000))
%timeit [i + 2 for i in a]

# Now with numpy

import numpy as np

a = np.array(a)        # push the data into a numpy array
%timeit a + 2


6.61 ms ± 213 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
73.7 µs ± 805 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Let's create an array consisting of True and False. Assume we want to count how many times we have a transition from True to False or the other way round. First we will use a classic Python loop

In [8]:
np.random.seed(123)
x = np.random.choice([False, True], size=100000)
x

array([False,  True, False, ...,  True, False, False])

In [9]:
def transitions(x):
    count = 0
    for i, j in zip(x[:-1], x[1:]):
        if j and not i:
            count += 1
    return count

transitions(x)
#%timeit transitions(x)

25096

In [10]:
np.count_nonzero(x[:-1] < x[1:])
#%timeit np.count_nonzero(x[:-1] < x[1:])

25096

In [11]:
# create numpy array
import numpy as np

# 1d array
a = np.array([1, 2, 3, 4 , 5, 6])

# 2d array
b = np.array([[1, 2, 3,4 , 5, 6],[1, 2, 3,4 , 5, 6]])

# 3d array
c = np.array([[[1,2,3,4], [5,6,7,8], [9,10,11,12],[13,14,15,16]],[[1,2,3,4], [5,6,7,8], [9,10,11,12],[13,14,15,16]]])

## Numpy functions to create arrays

In [12]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)                      # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)                     # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)                      # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)                     # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                            # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"
    
f = np.linspace(1, 15, 3)   # The linspace() function returns numbers evenly spaced over a specified intervals.
print(f)                           # Say we want 3 evenly spaced points from 1 to 15, we can easily use this.
                            # linspace() takes the third argument as the number of datapoints to be created
    
g= np.arange(3,10)           # Lists the natural numbers from 3 to 9, as the number in the second position is excluded
print(g)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.36086546 0.22535678]
 [0.50813044 0.60568391]]
[ 1.  8. 15.]
[3 4 5 6 7 8 9]


Numpy provides a large set of numeric datatypes that you can use to construct arrays.

In [16]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)                

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype) 

x = np.array([1, 2], dtype="int8")  # Select the datatype you want
x.dtype 

int64
float64


dtype('int8')

## Access and change array element

##### Array axis

<img src="images/axis.png"  />

In [17]:
a = np.array([1, 2, 3, 4 , 5, 6])
print(a)

# access and change array elements
a[0] = 2
a[1] = 100
a[2] = -4

a[0]
a[1]
a[2]
print(a)

[1 2 3 4 5 6]
[  2 100  -4   4   5   6]


In [2]:
# indexing 2d arrays
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12],[13,14,15,16]])
print(a)

print(a[0, 1]) 
print(a[2, 3])


# indexing 3d arrays
b = np.array([[[1,2,3,4], [5,6,7,8], [9,10,11,12],[13,14,15,16]],[[17,18,19,20], [21,22,23,24], [25,26,27,28],[30,31,32,33]]])
print(b)
print(b[0, 1, 1])
print(b[1, 3, 0])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2
12
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [30 31 32 33]]]
6
30


**Integer array indexing**: When slicing, the resulting array will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays. 

In [3]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])  
print(a)
# An example of integer array indexing.

a[[0, 1, 2], [0, 1, 0]]  

[[1 2]
 [3 4]
 [5 6]]


array([1, 4, 5])



**Slicing:** Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array


In [4]:
#slicing
print(a)
aa = a[:3, 1:3]
print(aa)

print(b) 
bb = b[:3, 1:3, 1:]
bb

[[1 2]
 [3 4]
 [5 6]]
[[2]
 [4]
 [6]]


NameError: name 'b' is not defined

In [5]:
print(a)
a[0, 1]  
aa[0, 0] = 10    #!! Careful changing the slice changes also original data
a[0, 1]

[[1 2]
 [3 4]
 [5 6]]


10

In [6]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12],[13,14,15,16]])

# Accessing rows
print(a[1, :])
print(a[1:3, :])
a[[1,2], :]


[5 6 7 8]
[[ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
# Accessing columns
print(a[:, 1])
print(a[:, 1:3])
a[:, [1]]

[ 2  6 10 14]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


array([[ 2],
       [ 6],
       [10],
       [14]])

In [7]:
# indexing with arrays of indices
x = np.arange(10)**2                       # creates array with first 10 squares numbers
print(x)

ind1 = np.array( [ 1,1,3,8,5 ] )           # create array of indices
print(x[ind1])                         

ind2 = np.array( [ [ 3, 4], [ 9, 7 ] ] )    # create bidimensional array of indices
x[ind2]                                  

[ 0  1  4  9 16 25 36 49 64 81]
[ 1  1  9 64 25]


array([[ 9, 16],
       [81, 49]])

**Boolean array indexing:** Boolean array indexing lets you pick out arbitrary elements of an array. You can also create for example boolean mask arrays

In [8]:
#Boolean array
a=np.array( [ 1,1,3,8,5 ] )   
boolarray = (a > 2) 
print(boolarray)

e = np.random.random((8,12))
print(e)
mask=np.array([1,1,0,0,1,0,1,1], dtype=bool) 
print(mask)
e[mask,1]

[False False  True  True  True]
[[0.70007209 0.69076262 0.179221   0.81085232 0.8842527  0.20224591
  0.72826393 0.20089126 0.28691436 0.94352134 0.33373921 0.09289539]
 [0.62119028 0.88732467 0.79709056 0.98143515 0.02992656 0.73523305
  0.76395045 0.60704814 0.83597265 0.64551206 0.73820148 0.25100039]
 [0.19236384 0.99699675 0.2367263  0.77543314 0.78185755 0.61801954
  0.33096821 0.76343582 0.83062391 0.25664773 0.17264261 0.27500879]
 [0.879963   0.03424989 0.8743007  0.79462705 0.3392394  0.49042242
  0.99129787 0.4654695  0.75005417 0.32513604 0.27125888 0.29025494]
 [0.32495367 0.66376438 0.06895275 0.39493094 0.98889611 0.82667999
  0.98411342 0.15739126 0.47968262 0.78085749 0.65251108 0.71862532]
 [0.16586702 0.35692201 0.49771117 0.96031668 0.47272008 0.29956056
  0.33838392 0.3812713  0.10940008 0.89633065 0.95324392 0.54291328]
 [0.04274919 0.5257726  0.00103512 0.43591657 0.78283897 0.66161267
  0.48660086 0.88905449 0.26399022 0.37155761 0.32272218 0.96919995]
 [0.71659

array([0.69076262, 0.88732467, 0.66376438, 0.5257726 , 0.63782542])

<img src="images/select.png"  />

## Array math

Basic mathematical functions operate **elementwise** on arrays. 

In [ ]:
arr = np.arange(1,21)          # Numbers from 1 to 20
arr
arr * arr             # Multiplies each element by itself 
arr - arr             # Subtracts each element from itself
arr + arr             # Adds each element to itself
arr / arr             # Divides each element by itself

Of course they are also available as functions  numpy

In [ ]:
x = np.array([[1,2,3,4],[5,6,7,8]])
y = np.array([[7,8,9,10],[11,12,13,14]])

# Elementwise sum
np.add(x, y)

# Elementwise difference
np.subtract(x, y)

# Elementwise product
np.multiply(x, y)

# Elementwise division
np.divide(x, y)

# Elementwise square root
np.sqrt(x)

All array objects have some "statistical" methods (e.g. mean,min,max,std).

In [ ]:
x.mean()
x.min()
x.max()
x.std()
x.max(axis=0)      #Maximum value of an array row
x.cumsum(axis=1)   #Cumulative sum of the elements

You can also easily calculate the square root of your arrays with np.exp() and np.sqrt(), or calculate the sines or cosines of your array with np.sin() and np.cos(). 

In [ ]:
np.exp(x)
np.sqrt(x)
np.cos(x)
np.sin(x)

Numpy also provides functions to deal with NaN values

In [ ]:
# with nan values
a = np.array([[1, 2], [3, np.nan]])
a.min()
np.nanmin(a)

In [ ]:
# using dot function for inner product of vector,
# multiply a vector by a matrix and multiply matrices

# create vector
m = np.array([4,8,54])
n = np.array([55, 15,5])

m
n

# vector product
m.dot(n)
np.dot(m, n)


In [ ]:
# Arithmetic operations will be done elementwise

Temp_in_C=np.array([25.,22.,17.,19.,30.])

Temp_in_F = 1.8*Temp_in_C+32

Temp_in_F

### Array manipulation

It is often easier to understand how several numpy functions work by visualizing the results. Therefor we will use
the seaborn library

In [ ]:
import seaborn as sns

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,12,13]])
sns.heatmap(a)

In [ ]:
# Transpose
#ns.heatmap(a.T)

# Tiling
#sns.heatmap(np.tile(a,(2,2)))

# Reshaping
#sns.heatmap(np.reshape(a, (4,3)))

# Concatenate
#sns.heatmap(np.concatenate((a,a),axis=1) )

# Stack arrays vertically (row-wise) 
#sns.heatmap(np.vstack((a,a)))   

# Stack arrays horizontal
#fstack = np.hstack((a,a))                    

### Broadcasting 
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations.You’ve already seen that operations between two NumPy arrays (of equal size) operate element-wise

In [ ]:
a = np.array([1.5, 2.5, 3.5])
b = np.array([10., 5., 1.])
a / b

But, what about unequally sized arrays? This is where broadcasting comes in:

<img src="images/numpy_broadcasting.png"  />

http://scipy-lectures.org/_images/numpy_broadcasting.png

In [ ]:
# classic Python
import numpy as np

x = np.array([[1,2,3,4,5,6,4,3,4,5,6,6,5,4,3,6], [4,5,6,7,6,5,4,3,4,5,6,6,5,4,3,6], [7,8,9,5,6,7,5,3,4,5,6,6,5,4,3,6], [10, 11, 12,2,3,4,5,3,4,5,6,6,5,4,3,6]])
v = np.array([1, 0, 1,0,1,1,0,0,0,1,2,2,1,0,0,1])
y = np.empty_like(x) 


for i in range(4): y[i, :] = x[i, :] + v

print(y)

In [ ]:
# Numpy
import numpy as np

x = np.array([[1,2,3,4,5,6,4,3,4,5,6,6,5,4,3,6], [4,5,6,7,6,5,4,3,4,5,6,6,5,4,3,6], [7,8,9,5,6,7,5,3,4,5,6,6,5,4,3,6], [10, 11, 12,2,3,4,5,3,4,5,6,6,5,4,3,6]])
v = np.array([1, 0, 1,0,1,1,0,0,0,1,2,2,1,0,0,1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  

In [ ]:
%timeit for i in range(4): y[i, :] = x[i, :] + v
%timeit y = x + v 

### Array programming in action: Clustering




Let’s say that you have a 2d array X and a 2d array of multiple (x, y) “proposed” centroids. Algorithms such as K-Means clustering work by randomly assigning initial “proposed” centroids, then reassigning each data point to its closest centroid. From there, new centroids are computed, with the algorithm converging on a solution once the re-generated labels (an encoding of the centroids) are unchanged between iterations. A part of this iterative process requires computing the Euclidean distance of each point from each centroid:

In [ ]:
from sklearn.datasets import make_blobs
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

X = make_blobs(n_samples=200, n_features=2, centers=4, cluster_std=1.6)
X=X[0]
X

In [ ]:
sns.scatterplot(X[:,0],X[:,1])

First write a function that initializes k centroids by randomly selecting them from the data points

In [ ]:
def initialize_centroids(points, k):
    centroids = points.copy()
    np.random.shuffle(centroids)
    return centroids[:k]

In [ ]:
centroids = initialize_centroids(X, 4)
centroids 


In [ ]:
import matplotlib.pyplot as plt
 
grid = sns.JointGrid(X[:,0],X[:,1], space=0, size=6, ratio=50)
grid.plot_joint(plt.scatter, color="g")
plt.scatter(centroids[:,0], centroids[:,1], color='r')

Now let's define a function that returns the closest centroid for each point.

In [ ]:
def closest_centroid(X, centroids):
    distances = np.sqrt(((X - centroids[:, np.newaxis])**2).sum(axis=2))
    return np.argmin(distances, axis=0)

closest = closest_centroid(X, centroids)
closest

In [ ]:
def move_centroids(X, closest, centroids):
    return np.array([X[closest==k].mean(axis=0) for k in range(centroids.shape[0])])

In [ ]:
centroids = initialize_centroids(X, 4)

In [ ]:
runs=[1,2,3,4,5,6,7,8,9]

for run in runs:
    closest = closest_centroid(X, centroids)
    centroids = move_centroids(X, closest, centroids)

    grid = sns.JointGrid(X[:,0],X[:,1], space=0, size=6, ratio=50)
    grid.plot_joint(plt.scatter, color="g")
    plt.scatter(centroids[:,0], centroids[:,1], color='r')

### Excercise 6

- Create a null vector of size 10
- Create a random sorted vector of size 10
- Create a 3x3 matrix with values ranging from 0 to 8
- Create a 5x5 array with 2 on the border and 0 inside 
- Create a 8x8 matrix and fill it with a checkerboard pattern
- Create a random array and subtract the mean of each row of a matrix 


Additional:
- Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinate
- Consider a random vector with shape (100,2) representing coordinates, find point by point distances 

## Powerful pandas

<img src="images/pandas.png"  width=300 align=right />


Pandas is a very powerful and flexible tool for data munging and preparing. 

Pandas deals with 3 data structures:
- **Series**: homogeneous 1-dimensional array
- **DataFrames**: heterogenous 2-dimensional array
- **Panel**: heterogenous 3-dimensional array


<img src="images/dataframe.png" width=600   />

## Create a pandas series

In [ ]:
import pandas as pd
import numpy as np


data = np.array(['Dave','Jim','Rosalee','Alex','Lucy','Anna'])
s = pd.Series(data)
s


# You can also create a series from dict
data = {'Dave' : 0., 'Jim' : 1., 'Rosalee' : 2.,'Alex': 3., 'Lucy': 4., 'Anna':5.}
s = pd.Series(data,index=['Dave','Jim','Rosalee','Alex','Lucy','Anna'])
s

#You can access the data from a series with the postiion
s = pd.Series([0.,1.,2.,3.,4.,5.,],index=['Dave','Jim','Rosalee','Alex','Lucy','Anna'])
type(s)

## Accessing pandas series

In [ ]:
##retrieve the first element
s[0]

#retrieve the first 2 element
s[:2]


##retrieve the last 2 element
s[-2:]

# And you can access data from a series using an index
s['Dave']


# multiple indices
s[['Dave', 'Alex', 'Lucy']]

## Pandas DataFrame

In [ ]:
data = [['Dave',35],['Jim',40],['Rosalee',37],['Alex',24],['Lucy',28],['Anna',45]]
df = pd.DataFrame(data,columns=['Name','Age'])
df

# changing data type with dtype

data = [['Dave',35],['Jim',40],['Rosalee',37],['Alex',24],['Lucy',28],['Anna',45]]
df = pd.DataFrame(data,columns=['Name','Age'],dtype="float")
df

# you can also combine multiple dictionaries with different data types

df2 = pd.DataFrame({ 'Number' : np.array([3] * 6,dtype='int32'),
                    'Time' : pd.Timestamp.today(),
                    'Name' : pd.Series(['Dave','Jim','Rosalee','Alex','Lucy','Anna'], index=list(range(6))),
                    'Age' : np.array([25,40,37,24,28,45]),
                    'Sex' : pd.Categorical(["male","male","female","male","female","female"])})
df2

In [ ]:
pd.DataFrame({"a" : [4 ,5, 6], "b" : [7, 8, 9], "c" : [10, 11, 12]},    index = pd.MultiIndex.from_tuples([('d',1),('d',2),('e',2)],names=['n','v']))

## Reshaping data

In [ ]:
df= pd.DataFrame([[4, 7, 10],[5, 8, 11],[6, 9, 12]], index=[1, 2, 3], columns=['a', 'b', 'c'])
df

df = pd.melt(df)
df

df2 = pd.DataFrame({ 'Number' : np.array([3] * 6,dtype='int32'),
                    'Time' : pd.Timestamp.today(),
                    'Name' : pd.Series(['Dave','Jim','Rosalee','Alex','Lucy','Anna'], index=list(range(6))),
                    'Age' : np.array([25,40,37,24,28,45]),
                    'Sex' : pd.Categorical(["male","male","female","male","female","female"]),
                    'Grade' : np.array([2,4,3,2,2,5]),
                   })
df3 = pd.pivot_table(df2,values="Age", index='Sex', columns='Grade')

df3

In [ ]:
df1= pd.DataFrame([[4, 7, 10],[5, 8, 11],[6, 9, 12]], index=[1, 2, 3], columns=['a', 'b', 'c'])
df2= pd.DataFrame([[4, 7, 10],[5, 8, 11],[6, 9, 12]], index=[1, 2, 3], columns=['d', 'e', 'f'])

pd.concat([df1,df2])
pd.concat([df1,df2], axis=1)

## Working with actual data

##### The Berkeley Earth Surface Temperature Data Set

The Berkeley Earth Surface Temperature Study combines 1.6 billion temperature reports from 16 pre-existing archives. It is nicely packaged and allows for slicing into interesting subsets (for example by country). They publish the source data and the code for the transformations they applied. They also use methods that allow weather observations from shorter time series to be included, meaning fewer observations need to be thrown away.

Data

- Global Land and Ocean-and-Land Temperatures (GlobalTemperatures.csv)
- Global Average Land Temperature by Country (GlobalLandTemperaturesByCountry.csv)
- Global Average Land Temperature by State (GlobalLandTemperaturesByState.csv)
- Global Land Temperatures By Major City (GlobalLandTemperaturesByMajorCity.csv)
- Global Land Temperatures By City (GlobalLandTemperaturesByCity.csv)

## Reading data into pandas

In [ ]:
import os
import numpy as np
import pandas as pd

# os.chdir("/home/steve/SpatialPythonCourse2020") # set your working directory first, e.g.
# Hint: [Control + L] in your working directory to jump to the directory link

data = './Data/non-spatial/GlobalLandTemperatures/GlobalLandTemperaturesByCountry.csv'

df = pd.read_csv(data, sep=',')
df

## Basic information

- df.shape:            (rows,columns)        
- df.index:           Describe index 
- df.columns:          Describe DataFrame columns
- df.info():           Info on DataFrame
- df.count():          Number of non-NA value

Pandas provides a lot of nice functions which make data manipulation is quite easy. Tab completion for column names (as well as public attributes) is automatically enabled.
Just use: df.<TAB>

In [ ]:
df.head()              # show data head

In [ ]:
df.tail()               # show data tail

In [ ]:
df.index               # display index

In [ ]:
df.columns             # display column names

In [ ]:
df.values              # display underlying numpy data

In [ ]:
sort = df.sort_values(by='AverageTemperature')
sort.head()

## Accessing data

For selecting data parts we can use the classic Python/Numpy indexing operators [] and attribute operator. Additionally pandas also provides optimized methods

In [ ]:
# You can access an index directly as an attribute:
print(df.dt)
# or
print(df['dt'])

In [ ]:
# slicing inside of [] slices the rows
df[:5]
df[::-1]

In [ ]:
df.iloc[0]         # select first row
df.iloc[1]         # select second row
df.iloc[-1]        # select last row
df.iloc[:,0]       # select first column
df.iloc[:,1]       # select second column
df.loc[[0],['Country','AverageTemperature']] # select single value by row number and column label

In [ ]:
# Select by condition
df_BFA = df.loc[df['Country'] == 'Burkina Faso']
df_BFA.head()

In [ ]:
# Select by multiple condition
dfsub = df.loc[(df['Country'] == 'Burkina Faso') & (df['dt'] >= '1990-01-01')]
dfsub.head()

In [ ]:
# dropping and adding columns

country = df['Country'] 
df2 =df.drop('Country', axis=1)
df2.head(3)

df2['Country'] = country
df2.head(3)

## Advanced indexing

In [ ]:
df.loc[:,df.isnull().any()]              #Select cols with NaN
df.loc[:,df.notnull().all()]             #Select cols without NaN  Indexing With isin

In [ ]:
df.where(df['AverageTemperature'] > 0) 

## Data manipulation

Renaming the columns and the row index

In [ ]:
# rename columns
df.columns = ['dt','AverageTemperature', 'Uncertainty', 'Country']
df.head()
df0= df.rename(columns = {'dt':'datetime'})
df0.head()

# rename rows
df1 = df0.set_index('datetime')                   
df1.head()
df2 = df1.reset_index()            
df2.head()

In [ ]:
# Sorting values
df.sort_values('AverageTemperature')                   #Order rows by values of a column (low to high).
df.sort_values('AverageTemperature', ascending=False)   #Order rows by values of a column (high to low).
df2 = df.set_index('dt')
df2.sort_index()

## Summarize Data

In [ ]:
len(df)                 # of rows in DataFrame.
df['Country'].value_counts()  # Count number of rows with each unique value of variable
df['Country'].nunique()       # of distinct values in a column

Pandas provides a large set of summary functions that operate on different kinds of pandas object

- **sum():**                 Sum values of each object.
- **count():**               Count non-NA/null values of each object.
- **median():**              Median value of each object.
- **quantile([0.25,0.75]):** Quantiles of each object.
- **apply(function):** Apply function to each object.
- **min():** Minimum value in each object.
- **max():** maximum value in each object.
- **mean():** Mean value of each object.
- **var():** Variance of each object.
- **std():** Standard deviation of each object

## Handling Missing Data

In [ ]:
df.head()
df2 = df.dropna() #Drop rows with any column having NA/null 
df2.head()
df3 = df.fillna(-999) # fill na values
df3.head()

## Group Data

In [ ]:
df.groupby(by="Country")      #group by values in column 
df.groupby(['dt'])['AverageTemperature'].mean()

## Apply functions

In [ ]:
# Apply functions to dataframe
def cel2fahr(x):
    
    x = 1.8 * x + 32
    return(x)    

def fahr2cel(x):
    
    x = (x - 32) / 1.8
    return(x)

In [ ]:
df["AverageTemperatureFahrenheit"] = df["AverageTemperature"].apply(cel2fahr)

df.head()

In [ ]:
# Writing pandas data to file
df.to_csv("Data/non-spatial/GlobalLandTemperatures/GSTbyCountry_annual.csv")

## Exercise 7

- Import ***GlobalLandTemperaturesByMajorCity.csv***
- Look at the first 5 entries
- Print the name of all the columns
- What is the number of observations in the dataset?
-  Display a summary of the basic information about this DataFrame and its data.
- Select just the 'AverageTemperature' and 'City' columns from the DataFrame
- Count the number of cities in the dataset
- Calculate the mean temperature for each city over all years. Sort the values in the 'AverageTemperature' - in decending order
- Calculate the maximal AverageTemperature in european cities between 1990 and 2013

In [ ]:
please in the exercise7 intead of writing all the city name in europe I thing it is better to find them by 
the coordinates. Thus, I have tried this but it is giving me some countries out of europe
#Calculate the maximal AverageTemperature in european  
#cities between 1990 and 2013 
avt_cityc = df[['dt','City','AverageTemperature','Latitude','Longitude']] 
avt_cityc.rename(columns = {'dt':'date', 'AverageTemperature': 'AverageTemp', 'Latitude':'Lat', 'Longitude':'Lon'})  
 
eur_city = avt_cityc[avt_cityc['Latitude'].between('35N', '75N') & (avt_cityc['Longitude'].between('25N', '60N'))]
print(temp_city.head(5))
temp_city = temp.loc[:,['AverageTemperature','City']]
temp_europe = temp.loc[((temp['Latitude'] >= '35N') & (temp['Latitude'] <= '70N'))  
& ((temp['Longitude'] >= '20W') & (temp['Longitude'] <= '60E'))  
& ((temp['dt'] >= '1990-01-01') & (temp['dt'] <= '2013-12-31'))]

 ## Visualize data with python

Producing high-quality graphics is one of the main reasons for doing statistical computing. For this purpose, we will use the matplotlib library, which is probably the most used python library for 2D-graphics. Matplotlib is the "grandfather" library of data visualization with Python. It was created by John Hunter. Matplotlib allows a quick data visualization and the creation of publication-quality figures.
Import matplotlib's pyplot module as well as numpy and pandas.
(Pyplot is a module in the matplotlib package. The module allows you to implicitly and automatically create figures and axes)

Some of the major Pros of Matplotlib are:

- easy to get started for simple plots
- custom labels and texts
- control of every element in a figure
- high-quality output in many formats
 

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

Let´s start with something easy. The code below creates a basic plot. The np.linspace function is used to create an array with evenly spaced numbers over a specified interval.
In Matplotlib the plot() functions is used to create the plot. If want display the plot you have to use the show() function.

In [ ]:
import random
# Make the plot reproducible
random.seed(1)
# Allow plotting in the notebook
%matplotlib inline
# Create some fake data
data1 = [random.randint(0, 50) for i in range(70)]

In [ ]:
plt.plot(data1, "-")

In [ ]:
plt.plot(data1, "*")

#### Basic Matplotlib Commands

We can create a very simple line plot using the following code 

In [ ]:
x = np.linspace(0, 5, 11)
y = x ** 2

In [ ]:
plt.plot(x, y, 'r') # 'r' == red
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.title('Title')
plt.show()

In [ ]:
# Create a second dataset to plot also
import random
random.seed(0)
data2 = [random.randint(0, 50) for i in range(70)]
# Make the plotting
plt.plot(data1, "-", color="black", label="data1")
plt.plot(data2, "-", color="red", label="data2")
plt.xlabel("Index")
plt.ylabel("Data")
# Also label the figure as a whole
plt.title("Two wonderful graphs")
# And finally simply call the legend 
plt.legend()
plt.show()

####  Object Oriented Method

The main idea in using the more formal Object Oriented method is to create figure objects and then just call methods or attributes off of that object.

<img src="images/matplot.png"/>


In [ ]:
# Create Figure (empty canvas)
fig = plt.figure()

# Add set of axes to figure
axes = fig.add_axes([0.1, 0.1, 0.8, 0.8]) # left, bottom, width, height (range 0 to 1)

# Plot on that set of axes
axes.plot(x, y, 'b')
axes.set_xlabel('Label X') # Notice the use of set_ to begin methods
axes.set_ylabel('Label Y')
axes.set_title('Title')



Although this looks more complicated using this method gives us full control over the plot

In [ ]:
# Creates blank canvas
fig = plt.figure()

axes1 = fig.add_axes([0.1, 0.1, 0.8, 0.8]) # main axes
axes2 = fig.add_axes([0.2, 0.5, 0.4, 0.3]) # inset axes

# Larger Figure Axes 1
axes1.plot(x, y, 'b')
axes1.set_xlabel('X_label_axes2')
axes1.set_ylabel('Y_label_axes2')
axes1.set_title('Axes 2 Title')

# Insert Figure Axes 2
axes2.plot(y, x, 'r')
axes2.set_xlabel('X_label_axes2')
axes2.set_ylabel('Y_label_axes2')
axes2.set_title('Axes 2 Title');

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Figure size
plt.figure(figsize=(8, 6), dpi=80)


# new subplot 
plt.subplot(1, 1, 1)
X = np.linspace(-np.pi, np.pi, 256, endpoint=True)
C, S = np.cos(X), np.sin(X)
# Plot cosine 
plt.plot(X, C, color="red", linewidth=4.0, linestyle="-",label='cosine')
# Plot sine 
plt.plot(X, S, color="yellow", linewidth=1.0, linestyle="-",label='sine')
# X-axes limits
plt.xlim(-4.0, 4.0)
# X-axes ticks
plt.xticks(np.linspace(-4, 4, 9, endpoint=True))
# Y-axes limits
plt.ylim(-1.0, 1.0)
# Y-axes ticks
plt.yticks(np.linspace(-1, 1, 5, endpoint=True))
# Save figure using 72 dots per inch
# plt.savefig("exercice_2.png", dpi=72)
plt.legend(loc='upper left')
# Show result on screen
plt.show()

Let's make some plots with some real data

In [ ]:
import pandas as pd

global_temp=pd.read_csv("Data/non-spatial/GlobalLandTemperatures/GlobalLandTemperaturesByCountry.csv")
global_temp.head()

In [ ]:
# Average temp by year
global_temp['dt'] = pd.to_datetime(global_temp['dt'])

# Set the datetime column as the index
global_temp.index = global_temp['dt'] 
global_temp=global_temp.groupby([global_temp.index.year])['AverageTemperature','AverageTemperatureUncertainty'].mean().reset_index()
print(global_temp)


In [ ]:
import matplotlib.pyplot as plt

fig = plt.figure(figsize=[20,8])
ax = plt.axes()
line, = ax.plot(global_temp['dt'], global_temp['AverageTemperature'], lw=2) # lw = linewidth
plt.xticks(rotation='vertical')
plt.show()


In [ ]:
plt.figure(figsize=(12, 6))
plt.scatter(global_temp['dt'], global_temp['AverageTemperature'], c=global_temp['AverageTemperature'], s=150, alpha=0.6, edgecolors='none', cmap='viridis')
plt.grid(True)
plt.title("Average Global Temperatures")
plt.xlabel("Year")
plt.ylabel("Temperature (Celsius)")
plt.show()

In [ ]:
plt.figure(figsize=(12, 6))
plt.plot(global_temp['dt'], (global_temp['AverageTemperature'] + global_temp['AverageTemperatureUncertainty']), c='purple', label='Average Uncertainty Field')
plt.plot(global_temp['dt'], (global_temp['AverageTemperature'] - global_temp['AverageTemperatureUncertainty']), c='purple')
plt.fill_between(global_temp['dt'], (global_temp['AverageTemperature'] + global_temp['AverageTemperatureUncertainty']), (global_temp['AverageTemperature'] - global_temp['AverageTemperatureUncertainty']), facecolor='lightblue')
plt.plot(global_temp['dt'], global_temp['AverageTemperature'], linewidth=3, label='Average Temperature')
plt.grid(True)
plt.legend(loc='best')
plt.title("Average Global Temperatures and Uncertainty Field")
plt.xlabel("Year")
plt.ylabel("Temperature (Celsius)")
plt.show()

Another powerful Python visualization library is seaborn which is based on matplotlib. Seaborn can do the same things as matplotlib and it makes plotting easier. It is often preferred, because user think the default settings in seaborn are more pleasing then in matplotlib. And the good thing is, if you know matplotlib, seaborn is really easy to learn. 
Let´s try some nice example plots (More plot examples can be found on http://seaborn.pydata.org/). 

In [ ]:
import seaborn as sns
sns.set(style="darkgrid")
plt.figure(figsize=(13, 8))
ax = sns.scatterplot(global_temp['dt'], global_temp['AverageTemperature'], hue=global_temp['AverageTemperature'])

In [ ]:
plt.figure(figsize=(13, 8))
ax = sns.regplot(global_temp['dt'], global_temp['AverageTemperature'])

In [ ]:
global_temp=pd.read_csv("Data/non-spatial/GlobalLandTemperatures/GlobalLandTemperaturesByCountry.csv")
countries = ["Burkina Faso","Germany","Russia","Japan","Chile","Kanada"]

In [ ]:
temp=global_temp[(global_temp['dt'] >= '2000') & (global_temp['Country'].isin(countries))]
del temp['AverageTemperatureUncertainty']

In [ ]:
temp.boxplot(by='Country',figsize=[15,10])

In [ ]:
import seaborn as sns
sns.set(style="darkgrid")
plt.figure(figsize=(16, 10))
sns.boxplot(x='Country', y="AverageTemperature", data=temp, palette="coolwarm")

In [ ]:
import seaborn as sns
sns.set(style="darkgrid")
plt.figure(figsize=(16, 10))
sns.lineplot(x='dt', y="AverageTemperature", hue='Country' ,data=temp)

## Visualisation alternatives

Few years ago matplotlib was the only answer to the question: "How do I make plots in python?". But nowadays we have a lot of choices. Each library takes a slightly different approach to plotting data. Which one you use is up to you.

In [ ]:
import altair as alt
from vega_datasets import data

source = data.seattle_weather()

scale = alt.Scale(domain=['sun', 'fog', 'drizzle', 'rain', 'snow'],
                  range=['#e7ba52', '#a7a7a7', '#aec7e8', '#1f77b4', '#9467bd'])
color = alt.Color('weather:N', scale=scale)

# We create two selections:
# - a brush that is active on the top panel
# - a multi-click that is active on the bottom panel
brush = alt.selection_interval(encodings=['x'])
click = alt.selection_multi(encodings=['color'])

# Top panel is scatter plot of temperature vs time
points = alt.Chart().mark_point().encode(
    alt.X('monthdate(date):T', title='Date'),
    alt.Y('temp_max:Q',
        title='Maximum Daily Temperature (C)',
        scale=alt.Scale(domain=[-5, 40])
    ),
    color=alt.condition(brush, color, alt.value('lightgray')),
    size=alt.Size('precipitation:Q', scale=alt.Scale(range=[5, 200]))
).properties(
    width=550,
    height=300
).add_selection(
    brush
).transform_filter(
    click
)

# Bottom panel is a bar chart of weather type
bars = alt.Chart().mark_bar().encode(
    x='count()',
    y='weather:N',
    color=alt.condition(click, color, alt.value('lightgray')),
).transform_filter(
    brush
).properties(
    width=550,
).add_selection(
    click
)

alt.vconcat(
    points,
    bars,
    data=source,
    title="Seattle Weather: 2012-2015"
)

In [ ]:
import pandas as pd

global_temp=pd.read_csv("Data/non-spatial/GlobalLandTemperatures/GlobalLandTemperaturesByCountry.csv")
global_temp.head()

# Average temp by year
global_temp['dt'] = pd.to_datetime(global_temp['dt'])

# Set the datetime column as the index
global_temp.index = global_temp['dt'] 
global_temp=global_temp.groupby([global_temp.index.year])['AverageTemperature','AverageTemperatureUncertainty'].mean().reset_index()
print(global_temp)


In [ ]:
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)
iplot([go.Scatter(x=global_temp.index, y=global_temp.AverageTemperature)])

In [ ]:
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

trace_middle = go.Scatter(
    x=global_temp.dt, 
    y=global_temp.AverageTemperature,
    name = "High",
    line = dict(color = '#17BECF'),
    opacity = 0.8)

trace_high = go.Scatter(
    x=global_temp.dt, 
    y=global_temp.AverageTemperature+global_temp.AverageTemperatureUncertainty,
    name = "Temp",
    line = dict(color = '#7F7F7F'),
    opacity = 0.8)    
    
trace_low = go.Scatter(
    x=global_temp.dt,
    y=global_temp.AverageTemperature-global_temp.AverageTemperatureUncertainty,
    name = "Low",
    line = dict(color = '#7F7F7F'),
    opacity = 0.8)

data = [trace_high,trace_middle,trace_low]

layout = dict(
    title='Time Series with Rangeslider',
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=1,
                     label='1m',
                     step='month',
                     stepmode='backward'),
                dict(count=6,
                     label='6m',
                     step='month',
                     stepmode='backward'),
                dict(step='all')
            ])
        ),
        rangeslider=dict(
            visible = True
        ),
        type='date'
    )
)

fig = dict(data=data, layout=layout)
iplot(fig, filename = "Time Series with Rangeslider")

#### Exercise 8

- Calculate the mean temperature (all cities) for each year plot the data
- Calculate the mean temperature of cities in West Africa for each year (between 1990 and 2013). Create a plot with 4 graphs each showing the mean temperature for one season (spring, summer, autumn, winter) per year
- Calculate the temperature difference for each  city in 2010 and create a barplot showing the ranked temperature difference 